# Generated by Django 4.2.27 on 2026-02-02 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=255)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('seats', models.IntegerField(default=1)),
                ('purchase_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_subscription', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
                ('revoked_date', models.DateField(blank=True, null=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.softwarelicense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_licenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('license', 'user')},
            },
        ),
    ]
